// training.type.ts – Shared TypeScript types for the Digital Skills Training Platform
// Model: Bootcamp-style → Post → Apply → Shortlist → Live Training → Completion → Certificate

// ---------------------------------------------------------------------------
// 1.  TRAINING SESSION  (a single live meeting inside a training program)
// ---------------------------------------------------------------------------
export interface TrainingSession {
  id?: string;
  training_id?: string;
  /** Human-readable title, e.g. "Week 1 – Foundations" */
  title: string;
  description?: string;
  /** ISO date-time string when the session starts */
  scheduled_at: string;
  /** Duration in minutes */
  duration_minutes: number;
  /** ✅ AUTO-GENERATED: Link to the live meeting room (no manual input needed) */
  meeting_url?: string;
  /** ✅ AUTO-GENERATED: 6-digit password for meeting security */
  meeting_password?: string;
  /** 1-based ordering within the training */
  order_index: number;
  is_completed?: boolean;
  attendance_count?: number;
  created_at?: Date;
  updated_at?: Date;
}

export interface SessionAttendance {
  id?: string;
  session_id: string;
  enrollment_id: string;
  user_id: string;
  attended: boolean;
  attendance_marked_at?: Date;
  notes?: string;
}

// ✅ UPDATED: No meeting_url/meeting_password in create request (auto-generated)
export interface CreateSessionRequest {
  title: string;
  description?: string;
  scheduled_at: string; // ISO string from the client
  duration_minutes: number;
  // ✅ REMOVED: meeting_url (auto-generated by backend)
  // ✅ REMOVED: meeting_password (auto-generated by backend)
  order_index: number;
}

export interface UpdateSessionRequest extends Partial<CreateSessionRequest> {
  id?: string; // present when updating an existing session inside an update-training payload
  // ✅ Optional: Allow keeping existing meeting_url/password when updating
  meeting_url?: string;
  meeting_password?: string;
}

// ---------------------------------------------------------------------------
// 2.  TRAINING APPLICATION  (a job-seeker's bid to join a training)
// ---------------------------------------------------------------------------
export type ApplicationStatus = 'pending' | 'shortlisted' | 'rejected';

export interface TrainingApplication {
  id: string;
  training_id: string;
  user_id: string;
  /** Free-text motivation / cover letter supplied by the applicant */
  motivation?: string;
  status: ApplicationStatus;
  /** Timestamp when the employer shortlisted (or rejected) */
  reviewed_at?: Date;
  /** Notes left by the employer during review */
  employer_notes?: string;
  applied_at: Date;
  created_at: Date;
  updated_at: Date;

  // ---------- populated / computed at query time ----------
  user?: {
    id: string;
    first_name: string;
    last_name: string;
    email: string;
    profile_image?: string;
  };
  training?: Training;
}

export interface SubmitApplicationRequest {
  motivation?: string;
}

export interface ShortlistDecisionRequest {
  /** 'shortlisted' | 'rejected' */
  decision: 'shortlisted' | 'rejected';
  employer_notes?: string;
}

// ---------------------------------------------------------------------------
// 3.  TRAINING ENROLLMENT  (created only when an applicant is shortlisted)
// ---------------------------------------------------------------------------
export type EnrollmentStatus = 'enrolled' | 'completed' | 'not_completed' | 'dropped';

export interface TrainingEnrollment {
  id: string;
  training_id: string;
  user_id: string;
  application_id?: string;
  status: EnrollmentStatus;
  enrolled_at: Date;
  completed_at?: Date;

  // Evaluation criteria (as per system design)
  attendance_rate: number; // Percentage
  participation_score: number; // 0-100
  tasks_completed: number;
  tasks_total: number;

  // Completion
  completion_marked: boolean;

  // Certificate
  certificate_issued: boolean;
  certificate_url?: string;
  certificate_issued_at?: Date;

  created_at: Date;
  updated_at: Date;

  // ---------- populated ----------
  user?: {
    id: string;
    first_name: string;
    last_name: string;
    email: string;
    profile_image?: string;
  };
  training?: Training;
}

export interface MarkCompletionRequest {
  /** true = completed successfully; false = not completed */
  completed: boolean;
  attendance_rate?: number;
  participation_score?: number;
  tasks_completed?: number;
  tasks_total?: number;
  /** Optional employer notes on the trainee's performance */
  employer_notes?: string;
}

// ---------------------------------------------------------------------------
// 4.  TRAINING OUTCOME  (learning objective listed on the training post)
// ---------------------------------------------------------------------------
export interface TrainingOutcome {
  id?: string;
  training_id?: string;
  outcome_text: string;
  order_index: number;
  created_at?: Date;
}

export interface CreateTrainingOutcomeRequest {
  outcome_text: string;
  order_index: number;
}

export interface UpdateTrainingOutcomeRequest {
  id?: string;
  outcome_text?: string;
  order_index?: number;
}

// ---------------------------------------------------------------------------
// 5.  TRAINING REVIEW  (left by an enrolled trainee after completion)
// ---------------------------------------------------------------------------
export interface TrainingReview {
  id: string;
  training_id: string;
  user_id: string;
  rating: number; // 1-5
  review_text?: string;
  created_at: Date;
  updated_at: Date;

  user?: {
    id: string;
    first_name: string;
    last_name: string;
    profile_image?: string;
  };
}

export interface SubmitReviewRequest {
  rating: number;
  review_text?: string;
}

// ---------------------------------------------------------------------------
// 6.  TRAINING  (the core training-post entity)
// ---------------------------------------------------------------------------
export type TrainingStatus = 'draft' | 'published' | 'applications_closed' | 'in_progress' | 'completed';
export type TrainingLevel  = 'Beginner' | 'Intermediate' | 'Advanced';
export type TrainingCostType = 'Free' | 'Paid';
export type TrainingMode    = 'Online' | 'Offline';

export interface Training {
  id: string;
  title: string;
  description: string;
  category: string;
  level: TrainingLevel;
  /** Total expected hours of live instruction */
  duration_hours: number;
  cost_type: TrainingCostType;
  price: number;
  mode: TrainingMode;
  provider_id: string;
  provider_name: string;
  has_certificate: boolean;

  // Training content
  training_objectives?: string;
  skills_to_acquire?: string[];
  eligibility_requirements?: string;

  // Application
  application_deadline?: Date;
  application_url?: string;

  // ✅ FIXED: Use consistent date field names (database uses start_date/end_date)
  start_date?: Date;
  end_date?: Date;

  // Capacity
  max_participants?: number;
  current_participants: number;

  // Status
  status: TrainingStatus;

  // Metadata
  rating: number;
  total_students: number;
  thumbnail_url?: string;
  location?: string;
  created_at: Date;
  updated_at: Date;

  // Relations
  sessions?: TrainingSession[];
  outcomes?: TrainingOutcome[];
  session_count?: number;

  // User-specific data (populated for job seekers)
  has_applied?: boolean;
  applied?: boolean;
  application_status?: ApplicationStatus;
  is_enrolled?: boolean;
  enrolled?: boolean;
  enrollment_id?: string;
  attendance_rate?: number;
  participation_score?: number;
  certificate_issued?: boolean;
  certificate_url?: string;
  certificate_code?: string;
  progress?: number;
  tasks_completed?: number;
  tasks_total?: number;
}

// ---------------------------------------------------------------------------
// 7.  CREATE / UPDATE DTOs
// ---------------------------------------------------------------------------
export interface CreateTrainingRequest {
  title: string;
  description: string;
  category: string;
  level: TrainingLevel;
  duration_hours: number;
  cost_type: TrainingCostType;
  price?: number;
  mode: TrainingMode;
  provider_name: string;
  has_certificate: boolean;
  eligibility_requirements?: string;
  application_deadline?: string;
  
  // ✅ FIXED: Accept both naming conventions (for backward compatibility)
  // Backend will normalize to start_date/end_date
  training_start_date?: string;
  training_end_date?: string;
  start_date?: string;
  end_date?: string;
  
  thumbnail_url?: string;
  location?: string;
  max_participants?: number;
  // ✅ UPDATED: Sessions don't need meeting_url anymore (auto-generated)
  sessions: CreateSessionRequest[];
  outcomes: CreateTrainingOutcomeRequest[];
}

export interface UpdateTrainingRequest {
  title?: string;
  description?: string;
  category?: string;
  level?: TrainingLevel;
  duration_hours?: number;
  cost_type?: TrainingCostType;
  price?: number;
  mode?: TrainingMode;
  provider_name?: string;
  has_certificate?: boolean;
  eligibility_requirements?: string;
  application_deadline?: string;
  
  // ✅ FIXED: Accept both naming conventions (for backward compatibility)
  // Backend will normalize to start_date/end_date
  training_start_date?: string;
  training_end_date?: string;
  start_date?: string;
  end_date?: string;
  
  thumbnail_url?: string;
  location?: string;
  max_participants?: number;
  status?: TrainingStatus;
  /** When provided the existing sessions are replaced wholesale */
  sessions?: UpdateSessionRequest[];
  outcomes?: UpdateTrainingOutcomeRequest[];
}

// ---------------------------------------------------------------------------
// 8.  LIST / SEARCH
// ---------------------------------------------------------------------------
export interface TrainingFilters {
  category?: string;
  level?: string[];
  cost_type?: string[];
  mode?: string[];
  rating?: number;
  has_certificate?: boolean;
  status?: string[];
  provider_id?: string;
  search?: string;
}

export interface JobseekerTrainingFilters extends TrainingFilters {
  /** 'all' | 'applied' | 'not_applied' */
  application_status?: 'all' | 'applied' | 'not_applied';
  /** 'all' | 'enrolled' | 'completed' */
  enrollment_status?: 'all' | 'enrolled' | 'completed';
}

export interface TrainingSearchParams {
  search?: string;
  mode?: string;
  cost_type?: string;
  level?: string;
  category?: string;
  page?: number;
  limit?: number;
  sort_by?: 'created_at' | 'title' | 'rating' | 'total_students' | 'start_date';
  sort_order?: 'asc' | 'desc';
  status?: string;
  filters?: JobseekerTrainingFilters;
  include_sessions?: boolean;
  include_outcomes?: boolean;
}

export interface TrainingWithContext extends Training {
  has_applied: boolean;
  applied: boolean;
  is_enrolled: boolean;
  enrolled: boolean;
  application_status?: ApplicationStatus;
  enrollment_status?: EnrollmentStatus;
  applied_at?: Date;
  enrolled_at?: Date;
  completed_at?: Date;
}

export interface TrainingListResponse {
  success?: boolean;
  data?: {
    trainings: TrainingWithContext[];
  };
  trainings?: TrainingWithContext[];
  pagination: {
    current_page: number;
    total_pages: number;
    page_size: number;
    total_count: number;
    has_next: boolean;
    has_previous: boolean;
  };
  filters_applied?: JobseekerTrainingFilters;
}

// ---------------------------------------------------------------------------
// 9.  STATS
// ---------------------------------------------------------------------------
export interface TrainingStatsResponse {
  total_trainings: number;
  published_trainings: number;
  draft_trainings: number;
  suspended_trainings?: number;
  total_applications: number;
  pending_applications?: number;
  total_enrollments: number;
  total_completions: number;
  total_revenue: number;
  avg_rating: number;
  completion_rate: number;
  certificates_issued?: number;
  categories_breakdown?: { category: string; count: number }[];
  monthly_enrollments?: { month: string; count: number }[];
}

export interface JobseekerTrainingStats {
  total_applied: number;
  total_enrolled: number;
  completed_count: number;
  certificates_earned: number;
  total_spent?: number;
  monthly_activity?: { month: Date; count: number }[];
}

// ---------------------------------------------------------------------------
// 10. CERTIFICATE
// ---------------------------------------------------------------------------
export interface Certificate {
  id: string;
  enrollment_id: string;
  certificate_url: string;
  /** Unique human-readable code printed on the PDF */
  verification_code: string;
  issued_at: Date;
}

export interface CertificateGenerationRequest {
  enrollment_id: string;
}

// ---------------------------------------------------------------------------
// 11. NOTIFICATION
// ---------------------------------------------------------------------------
export type NotificationType =
  | 'new_training'
  | 'training_updated'
  | 'training_deleted'
  | 'training_suspended'
  | 'training_published'
  | 'application_submitted'
  | 'application_shortlisted'
  | 'application_rejected'
  | 'training_completed_mark'
  | 'certificate_issued'
  | 'new_enrollment';

// ---------------------------------------------------------------------------
// 12. GENERIC API WRAPPERS
// ---------------------------------------------------------------------------
export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  message?: string;
  errors?: string[];
  meta?: { timestamp?: Date; request_id?: string };
}

export interface PaginatedApiResponse<T> extends ApiResponse<T> {
  pagination?: {
    current_page: number;
    total_pages: number;
    page_size: number;
    total_count: number;
    has_next: boolean;
    has_previous: boolean;
  };
}

// ---------------------------------------------------------------------------
// 13. MISC UTILITIES  (kept for compatibility)
// ---------------------------------------------------------------------------
export type JobseekerTrainingStatus = 'available' | 'applied' | 'enrolled' | 'completed' | 'dropped';
export type ProgressMilestone = 25 | 50 | 75 | 100;

// ---------------------------------------------------------------------------
// 14. ATTENDANCE RECORD (system design addition)
// ---------------------------------------------------------------------------
export interface AttendanceRecord {
  session_id: string;
  enrollment_id: string;
  attended: boolean;
  notes?: string;
}

// ---------------------------------------------------------------------------
// 15. ✅ NEW: MEETING DETAILS (for meeting room validation)
// ---------------------------------------------------------------------------
export interface MeetingDetails {
  valid: boolean;
  message?: string;
  session?: {
    id: string;
    title: string;
    description?: string;
    scheduled_at: string;
    duration_minutes: number;
    meeting_password: string;
    training_title: string;
    provider_name: string;
    room_code: string;
  };
}